# delete any orphaned resources created by a Four Keys deployment

steps:  
  - name: gcr.io/$PROJECT_ID/fourkeys-builder
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        ### Delete Terraform state
        gsutil -m rm -r gs://$_TARGET_PROJECT-tf-state/terraform || true

        ### Delete all resources
        ./ci/project_cleaner.sh --project=$_TARGET_PROJECT || true

        echo "Turning off APIs"
        gcloud services disable compute.googleapis.com --project=$_TARGET_PROJECT --force
        gcloud services disable run.googleapis.com --project=$_TARGET_PROJECT --force
        gcloud services disable bigquery.googleapis.com --project=$_TARGET_PROJECT --force 
        gcloud services disable secretmanager.googleapis.com --project=$_TARGET_PROJECT --force
substitutions:
  _TARGET_PROJECT: fourkeys-tf-tests