### Work in progress! 
# This Cloud Build config will provision 4Keys infra using the modules in /terraform
# and then confirm that the dashboard is working correctly

steps:
# TODO: clean any existing artifacts

# [?]TODO: build containers

# debug
- id: debug
  name: 'gcr.io/$PROJECT_ID/fourkeys-builder'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      pwd
      ls -la

# create terraform config
- id: terraform config
  name: 'gcr.io/$PROJECT_ID/fourkeys-builder'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      cat > main.tf <<EOF
      module "fourkeys" {
        source    = "./terraform/modules/fourkeys"
        project_id = "$_TARGET_PROJECT"
        parsers   = ["github"]
        enable_build_images=true
        enable_apis=false
        region="us-east4"
        bigquery_region="US"
      }
      EOF

# intialize terraform
- id: terraform init
  name: 'gcr.io/$PROJECT_ID/fourkeys-builder'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      # configure remote terraform backend GCS
      cat > /workspace/backend.tf <<EOF
      terraform {
        backend "gcs" {
          bucket  = "$_TARGET_PROJECT-tf-state"
          prefix  = "terraform/state"
        }
      }
      EOF
      terraform init

# apply terraform
- id: terraform apply
  name: 'gcr.io/$PROJECT_ID/fourkeys-builder'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      terraform apply -auto-approve

# TODO: test installation


substitutions:
  _TARGET_PROJECT: fourkeys-testing-target-v1
