on:
  pull_request:
    paths:
      - '**.py'
  push:
    paths:
      - '**.py'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install nox
      - run: python3 -m nox
